export class $reconciliation$read {
    static COMMAND:string="reconciliation.read"

    static I_DATE1:string="date1"
    static I_DATE2:string="date2"
    static I_BANK_INCLUDE_CONCILIATED:string="bank_include_reconciliated"
    static I_BANK_CODE:string="bank_code"
    static I_LEDGER_FIELDS:string="ledger_fields"
    static I_BANK_FIELDS:string="bank_fields"
    static I_SUMMARY_FIELDS:string="summary_fields"
    static I_TYPE:string="type"
    static O_BANK_NAME:string="bank_name"
    static O_LEDGER_DATA:string="ledger_data"
    static O_LEDGER_DATA_ROW:string="row"
    static O_BANK_DATA:string="bank_data"
    static O_BANK_DATA_ROW:string="row"
    static O_SUMMARY:string="summary"
    static O_SUMMARY_ROW:string="row"
    static O_SUMMARY_ROW_DESCRIPTION:string="description"
    static O_SUMMARY_ROW_LEDGER_AMOUNT:string="ledger_amount"
    static O_SUMMARY_ROW_LEDGER_COUNT:string="ledger_count"
    static O_SUMMARY_ROW_BANK_AMOUNT:string="bank_amount"
    static O_SUMMARY_ROW_BANK_COUNT:string="bank_count"
    static O_SUMMARY_ROW_DIFFERENCE_AMOUNT:string="difference_amount"
    static O_SUMMARY_ROW_DIFFERENCE_COUNT:string="difference_count"
    static O_MESSAGE:string="message"
}