export class $maintenance$diagnose {
    static COMMAND:string="maintenance.diagnose"

    static I_SOURCE_SERVER:string="source_server"
    static I_SOURCE_DATABASE:string="source_database"
    static I_INVENTORY_PREFIXES:string="inventory_prefixes"
    static I_TRANSACTION_PREFIXES:string="transaction_prefixes"
    static I_RESET_COST_DATES:string="reset_cost_dates"
    static I_BASEDATE:string="basedate"
    static I_TABLES:string="tables"
    static I_TABLES_NAME:string="table_name"
    static I_ITEMS_TO_DIAGNOSE:string="items_to_diagnose"
    static I_ITEMS_TO_DIAGNOSE_ITEM:string="item"
    static I_REPORT_MAX_COUNT:string="report_max_count"
    static O_LOG:string="log"
    static O_ERRORS_FIXED:string="errors_fixed"
    static O_ERRORS_UNFIXED:string="errors_unfixed"
    static O_MESSAGE:string="message"
    static O_TOFIX:string="tofix"
    static O_TOFIX_ITEM:string="item"
    static O_TOFIX_ITEM_FIXID:string="fixid"
    static O_TOFIX_ITEM_DESCRIPTION:string="description"
    static O_TOFIX_ITEM_INSTRUCTIONS:string="instructions"
    static O_TOFIX_ITEM_XML:string="xml"
    static O_TOFIX_ITEM_XML_FIELDS:string="fields"
    static O_TOFIX_ITEM_XML_REALTABLENAME:string="realtablename"
}