export class $transaction$write {
    static COMMAND:string="transaction.write"

    static I_NUMBER:string="number"
    static I_CONTROLS:string="controls"
    static I_CONTROLS_FORCE_NUMBER:string="force_number"
    static I_TYPE:string="type"
    static I_TRANSACTION:string="transaction"
    static I_ENTRIES:string="entries"
    static I_ENTRIES_ENTRY:string="entry"
    static I_SAVE:string="save"
    static I_LEDGER:string="ledger"
    static I_LEDGER_ID_:string="id_"
    static I_LEDGER_ID_ROW:string="row"
    static I_LEDGER_ID_ROW_CODE:string="code"
    static I_LEDGER_ID_ROW_AMOUNT:string="amount"
    static I_APPROVAL_CODES:string="approval_codes"
    static I_APPROVAL_LOGIN:string="approval_login"
    static I_APPROVAL_PASSWORD:string="approval_password"
    static O_APPROVAL_MESSAGE:string="approval_message"
    static O_APPROVAL_CODES:string="approval_codes"
    static O_APPROVAL_PASSWORD_REQUIRED:string="approval_password_required"
    static O_MESSAGE:string="message"
    static O_NUMBER:string="number"
    static O_SAVED:string="saved"
    static O_SUMMARY:string="summary"
    static O_JOURNAL_NUMBER:string="journal_number"
    static O_LEDGER:string="ledger"
    static O_LEDGER_ID_:string="id_"
    static O_LEDGER_ID_TITLE:string="title"
    static O_LEDGER_ID_TOTAL:string="total"
    static O_LEDGER_ID_ROW:string="row"
    static O_LEDGER_ID_ROW_CODE:string="code"
    static O_LEDGER_ID_ROW_DESCRIPCION:string="description"
}