export class $journal$write {
    static COMMAND:string="journal.write"

    static I_NUMBER:string="number"
    static I_JOURNAL:string="journal"
    static I_ISPAYROLL:string="ispayroll"
    static I_ENTRIES:string="entries"
    static I_ENTRIES_ENTRY:string="entry"
    static I_APPROVAL_CODES:string="approval_codes"
    static I_APPROVAL_LOGIN:string="approval_login"
    static I_APPROVAL_PASSWORD:string="approval_password"
    static I_ADD_BANK_TAX_DEBIT:string="add_tax_debit"
    static O_APPROVAL_MESSAGE:string="approval_message"
    static O_APPROVAL_CODES:string="approval_codes"
    static O_APPROVAL_PASSWORD_REQUIRED:string="approval_password_required"
    static O_MESSAGE:string="message"
    static O_NUMBER:string="number"
    static O_SAVED:string="saved"
    static O_INTERCOMPANY:string="intercompany"
    static O_INTERCOMPANY_ENTRY:string="entry"
    static O_INTERCOMPANY_ENTRY_INDEX:string="index"
    static O_INTERCOMPANY_ENTRY_COMPANY:string="company"
    static O_INTERCOMPANY_ENTRY_LEDGER_CODE:string="ledger_code"
}